# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: lbspen_development
  username: postgres
  pool: 5
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: lbspen_test
  username: postgres
  pool: 5
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: lbspen_production
  username: postgres
  pool: 5
  password: postgres
  host: localhost